
S ::= schema name version platform

schema ::= <"Schema:"> int <newline>
name ::= <"Name:"> ident <newline>
version ::= <"Version:"> ident <newline>

platform ::= <"Platform"> <'{'> name version <'}'>

newline ::= '\n'
<ident> := #"\S+"
<int> ::= #"\d+"



