
configuration ::= schema name version platform

schema ::= <"Schema:"> int nl
name ::= <"Name:"> ident nl
version ::= <"Version:"> ident nl

platform ::= <"Platform"> <'{'> name version? <'}'>

<nl> ::= <'\n'>
<ident> := #"\S+"
<int> ::= #"\d+"

