// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: target/org.hyperledger.chaintool.meta.proto

package org.hyperledger.chaintool.meta;

public final class OrgHyperledgerChaintoolMeta {
  private OrgHyperledgerChaintoolMeta() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GetInterfaceParamsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.hyperledger.chaintool.meta.GetInterfaceParams)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code org.hyperledger.chaintool.meta.GetInterfaceParams}
   */
  public  static final class GetInterfaceParams extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.hyperledger.chaintool.meta.GetInterfaceParams)
      GetInterfaceParamsOrBuilder {
    // Use GetInterfaceParams.newBuilder() to construct.
    private GetInterfaceParams(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private GetInterfaceParams() {
      name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GetInterfaceParams(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.internal_static_org_hyperledger_chaintool_meta_GetInterfaceParams_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.internal_static_org_hyperledger_chaintool_meta_GetInterfaceParams_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfaceParams.class, org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfaceParams.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfaceParams parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfaceParams parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfaceParams parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfaceParams parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfaceParams parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfaceParams parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfaceParams parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfaceParams parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfaceParams parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfaceParams parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfaceParams prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.hyperledger.chaintool.meta.GetInterfaceParams}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.hyperledger.chaintool.meta.GetInterfaceParams)
        org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfaceParamsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.internal_static_org_hyperledger_chaintool_meta_GetInterfaceParams_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.internal_static_org_hyperledger_chaintool_meta_GetInterfaceParams_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfaceParams.class, org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfaceParams.Builder.class);
      }

      // Construct using org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfaceParams.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.internal_static_org_hyperledger_chaintool_meta_GetInterfaceParams_descriptor;
      }

      public org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfaceParams getDefaultInstanceForType() {
        return org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfaceParams.getDefaultInstance();
      }

      public org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfaceParams build() {
        org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfaceParams result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfaceParams buildPartial() {
        org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfaceParams result = new org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfaceParams(this);
        result.name_ = name_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfaceParams) {
          return mergeFrom((org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfaceParams)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfaceParams other) {
        if (other == org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfaceParams.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfaceParams parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfaceParams) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:org.hyperledger.chaintool.meta.GetInterfaceParams)
    }

    // @@protoc_insertion_point(class_scope:org.hyperledger.chaintool.meta.GetInterfaceParams)
    private static final org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfaceParams DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfaceParams();
    }

    public static org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfaceParams getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetInterfaceParams>
        PARSER = new com.google.protobuf.AbstractParser<GetInterfaceParams>() {
      public GetInterfaceParams parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new GetInterfaceParams(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<GetInterfaceParams> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetInterfaceParams> getParserForType() {
      return PARSER;
    }

    public org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfaceParams getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetInterfacesParamsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.hyperledger.chaintool.meta.GetInterfacesParams)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool IncludeContent = 1;</code>
     */
    boolean getIncludeContent();
  }
  /**
   * Protobuf type {@code org.hyperledger.chaintool.meta.GetInterfacesParams}
   */
  public  static final class GetInterfacesParams extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.hyperledger.chaintool.meta.GetInterfacesParams)
      GetInterfacesParamsOrBuilder {
    // Use GetInterfacesParams.newBuilder() to construct.
    private GetInterfacesParams(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private GetInterfacesParams() {
      includeContent_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GetInterfacesParams(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              includeContent_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.internal_static_org_hyperledger_chaintool_meta_GetInterfacesParams_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.internal_static_org_hyperledger_chaintool_meta_GetInterfacesParams_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfacesParams.class, org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfacesParams.Builder.class);
    }

    public static final int INCLUDECONTENT_FIELD_NUMBER = 1;
    private boolean includeContent_;
    /**
     * <code>optional bool IncludeContent = 1;</code>
     */
    public boolean getIncludeContent() {
      return includeContent_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (includeContent_ != false) {
        output.writeBool(1, includeContent_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (includeContent_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, includeContent_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfacesParams parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfacesParams parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfacesParams parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfacesParams parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfacesParams parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfacesParams parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfacesParams parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfacesParams parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfacesParams parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfacesParams parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfacesParams prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.hyperledger.chaintool.meta.GetInterfacesParams}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.hyperledger.chaintool.meta.GetInterfacesParams)
        org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfacesParamsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.internal_static_org_hyperledger_chaintool_meta_GetInterfacesParams_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.internal_static_org_hyperledger_chaintool_meta_GetInterfacesParams_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfacesParams.class, org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfacesParams.Builder.class);
      }

      // Construct using org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfacesParams.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        includeContent_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.internal_static_org_hyperledger_chaintool_meta_GetInterfacesParams_descriptor;
      }

      public org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfacesParams getDefaultInstanceForType() {
        return org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfacesParams.getDefaultInstance();
      }

      public org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfacesParams build() {
        org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfacesParams result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfacesParams buildPartial() {
        org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfacesParams result = new org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfacesParams(this);
        result.includeContent_ = includeContent_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfacesParams) {
          return mergeFrom((org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfacesParams)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfacesParams other) {
        if (other == org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfacesParams.getDefaultInstance()) return this;
        if (other.getIncludeContent() != false) {
          setIncludeContent(other.getIncludeContent());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfacesParams parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfacesParams) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean includeContent_ ;
      /**
       * <code>optional bool IncludeContent = 1;</code>
       */
      public boolean getIncludeContent() {
        return includeContent_;
      }
      /**
       * <code>optional bool IncludeContent = 1;</code>
       */
      public Builder setIncludeContent(boolean value) {
        
        includeContent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool IncludeContent = 1;</code>
       */
      public Builder clearIncludeContent() {
        
        includeContent_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:org.hyperledger.chaintool.meta.GetInterfacesParams)
    }

    // @@protoc_insertion_point(class_scope:org.hyperledger.chaintool.meta.GetInterfacesParams)
    private static final org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfacesParams DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfacesParams();
    }

    public static org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfacesParams getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetInterfacesParams>
        PARSER = new com.google.protobuf.AbstractParser<GetInterfacesParams>() {
      public GetInterfacesParams parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new GetInterfacesParams(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<GetInterfacesParams> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetInterfacesParams> getParserForType() {
      return PARSER;
    }

    public org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.GetInterfacesParams getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface InterfacesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.hyperledger.chaintool.meta.Interfaces)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .org.hyperledger.chaintool.meta.InterfaceDescriptor descriptors = 1;</code>
     */
    java.util.List<org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor> 
        getDescriptorsList();
    /**
     * <code>repeated .org.hyperledger.chaintool.meta.InterfaceDescriptor descriptors = 1;</code>
     */
    org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor getDescriptors(int index);
    /**
     * <code>repeated .org.hyperledger.chaintool.meta.InterfaceDescriptor descriptors = 1;</code>
     */
    int getDescriptorsCount();
    /**
     * <code>repeated .org.hyperledger.chaintool.meta.InterfaceDescriptor descriptors = 1;</code>
     */
    java.util.List<? extends org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptorOrBuilder> 
        getDescriptorsOrBuilderList();
    /**
     * <code>repeated .org.hyperledger.chaintool.meta.InterfaceDescriptor descriptors = 1;</code>
     */
    org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptorOrBuilder getDescriptorsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code org.hyperledger.chaintool.meta.Interfaces}
   */
  public  static final class Interfaces extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.hyperledger.chaintool.meta.Interfaces)
      InterfacesOrBuilder {
    // Use Interfaces.newBuilder() to construct.
    private Interfaces(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Interfaces() {
      descriptors_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Interfaces(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                descriptors_ = new java.util.ArrayList<org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor>();
                mutable_bitField0_ |= 0x00000001;
              }
              descriptors_.add(input.readMessage(org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          descriptors_ = java.util.Collections.unmodifiableList(descriptors_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.internal_static_org_hyperledger_chaintool_meta_Interfaces_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.internal_static_org_hyperledger_chaintool_meta_Interfaces_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.Interfaces.class, org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.Interfaces.Builder.class);
    }

    public static final int DESCRIPTORS_FIELD_NUMBER = 1;
    private java.util.List<org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor> descriptors_;
    /**
     * <code>repeated .org.hyperledger.chaintool.meta.InterfaceDescriptor descriptors = 1;</code>
     */
    public java.util.List<org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor> getDescriptorsList() {
      return descriptors_;
    }
    /**
     * <code>repeated .org.hyperledger.chaintool.meta.InterfaceDescriptor descriptors = 1;</code>
     */
    public java.util.List<? extends org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptorOrBuilder> 
        getDescriptorsOrBuilderList() {
      return descriptors_;
    }
    /**
     * <code>repeated .org.hyperledger.chaintool.meta.InterfaceDescriptor descriptors = 1;</code>
     */
    public int getDescriptorsCount() {
      return descriptors_.size();
    }
    /**
     * <code>repeated .org.hyperledger.chaintool.meta.InterfaceDescriptor descriptors = 1;</code>
     */
    public org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor getDescriptors(int index) {
      return descriptors_.get(index);
    }
    /**
     * <code>repeated .org.hyperledger.chaintool.meta.InterfaceDescriptor descriptors = 1;</code>
     */
    public org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptorOrBuilder getDescriptorsOrBuilder(
        int index) {
      return descriptors_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < descriptors_.size(); i++) {
        output.writeMessage(1, descriptors_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < descriptors_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, descriptors_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.Interfaces parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.Interfaces parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.Interfaces parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.Interfaces parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.Interfaces parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.Interfaces parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.Interfaces parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.Interfaces parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.Interfaces parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.Interfaces parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.Interfaces prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.hyperledger.chaintool.meta.Interfaces}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.hyperledger.chaintool.meta.Interfaces)
        org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfacesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.internal_static_org_hyperledger_chaintool_meta_Interfaces_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.internal_static_org_hyperledger_chaintool_meta_Interfaces_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.Interfaces.class, org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.Interfaces.Builder.class);
      }

      // Construct using org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.Interfaces.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDescriptorsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (descriptorsBuilder_ == null) {
          descriptors_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          descriptorsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.internal_static_org_hyperledger_chaintool_meta_Interfaces_descriptor;
      }

      public org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.Interfaces getDefaultInstanceForType() {
        return org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.Interfaces.getDefaultInstance();
      }

      public org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.Interfaces build() {
        org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.Interfaces result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.Interfaces buildPartial() {
        org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.Interfaces result = new org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.Interfaces(this);
        int from_bitField0_ = bitField0_;
        if (descriptorsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            descriptors_ = java.util.Collections.unmodifiableList(descriptors_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.descriptors_ = descriptors_;
        } else {
          result.descriptors_ = descriptorsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.Interfaces) {
          return mergeFrom((org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.Interfaces)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.Interfaces other) {
        if (other == org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.Interfaces.getDefaultInstance()) return this;
        if (descriptorsBuilder_ == null) {
          if (!other.descriptors_.isEmpty()) {
            if (descriptors_.isEmpty()) {
              descriptors_ = other.descriptors_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDescriptorsIsMutable();
              descriptors_.addAll(other.descriptors_);
            }
            onChanged();
          }
        } else {
          if (!other.descriptors_.isEmpty()) {
            if (descriptorsBuilder_.isEmpty()) {
              descriptorsBuilder_.dispose();
              descriptorsBuilder_ = null;
              descriptors_ = other.descriptors_;
              bitField0_ = (bitField0_ & ~0x00000001);
              descriptorsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getDescriptorsFieldBuilder() : null;
            } else {
              descriptorsBuilder_.addAllMessages(other.descriptors_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.Interfaces parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.Interfaces) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor> descriptors_ =
        java.util.Collections.emptyList();
      private void ensureDescriptorsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          descriptors_ = new java.util.ArrayList<org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor>(descriptors_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor, org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor.Builder, org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptorOrBuilder> descriptorsBuilder_;

      /**
       * <code>repeated .org.hyperledger.chaintool.meta.InterfaceDescriptor descriptors = 1;</code>
       */
      public java.util.List<org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor> getDescriptorsList() {
        if (descriptorsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(descriptors_);
        } else {
          return descriptorsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .org.hyperledger.chaintool.meta.InterfaceDescriptor descriptors = 1;</code>
       */
      public int getDescriptorsCount() {
        if (descriptorsBuilder_ == null) {
          return descriptors_.size();
        } else {
          return descriptorsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .org.hyperledger.chaintool.meta.InterfaceDescriptor descriptors = 1;</code>
       */
      public org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor getDescriptors(int index) {
        if (descriptorsBuilder_ == null) {
          return descriptors_.get(index);
        } else {
          return descriptorsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .org.hyperledger.chaintool.meta.InterfaceDescriptor descriptors = 1;</code>
       */
      public Builder setDescriptors(
          int index, org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor value) {
        if (descriptorsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDescriptorsIsMutable();
          descriptors_.set(index, value);
          onChanged();
        } else {
          descriptorsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.hyperledger.chaintool.meta.InterfaceDescriptor descriptors = 1;</code>
       */
      public Builder setDescriptors(
          int index, org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor.Builder builderForValue) {
        if (descriptorsBuilder_ == null) {
          ensureDescriptorsIsMutable();
          descriptors_.set(index, builderForValue.build());
          onChanged();
        } else {
          descriptorsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.hyperledger.chaintool.meta.InterfaceDescriptor descriptors = 1;</code>
       */
      public Builder addDescriptors(org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor value) {
        if (descriptorsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDescriptorsIsMutable();
          descriptors_.add(value);
          onChanged();
        } else {
          descriptorsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .org.hyperledger.chaintool.meta.InterfaceDescriptor descriptors = 1;</code>
       */
      public Builder addDescriptors(
          int index, org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor value) {
        if (descriptorsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDescriptorsIsMutable();
          descriptors_.add(index, value);
          onChanged();
        } else {
          descriptorsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.hyperledger.chaintool.meta.InterfaceDescriptor descriptors = 1;</code>
       */
      public Builder addDescriptors(
          org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor.Builder builderForValue) {
        if (descriptorsBuilder_ == null) {
          ensureDescriptorsIsMutable();
          descriptors_.add(builderForValue.build());
          onChanged();
        } else {
          descriptorsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.hyperledger.chaintool.meta.InterfaceDescriptor descriptors = 1;</code>
       */
      public Builder addDescriptors(
          int index, org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor.Builder builderForValue) {
        if (descriptorsBuilder_ == null) {
          ensureDescriptorsIsMutable();
          descriptors_.add(index, builderForValue.build());
          onChanged();
        } else {
          descriptorsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.hyperledger.chaintool.meta.InterfaceDescriptor descriptors = 1;</code>
       */
      public Builder addAllDescriptors(
          java.lang.Iterable<? extends org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor> values) {
        if (descriptorsBuilder_ == null) {
          ensureDescriptorsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, descriptors_);
          onChanged();
        } else {
          descriptorsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .org.hyperledger.chaintool.meta.InterfaceDescriptor descriptors = 1;</code>
       */
      public Builder clearDescriptors() {
        if (descriptorsBuilder_ == null) {
          descriptors_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          descriptorsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .org.hyperledger.chaintool.meta.InterfaceDescriptor descriptors = 1;</code>
       */
      public Builder removeDescriptors(int index) {
        if (descriptorsBuilder_ == null) {
          ensureDescriptorsIsMutable();
          descriptors_.remove(index);
          onChanged();
        } else {
          descriptorsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .org.hyperledger.chaintool.meta.InterfaceDescriptor descriptors = 1;</code>
       */
      public org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor.Builder getDescriptorsBuilder(
          int index) {
        return getDescriptorsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .org.hyperledger.chaintool.meta.InterfaceDescriptor descriptors = 1;</code>
       */
      public org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptorOrBuilder getDescriptorsOrBuilder(
          int index) {
        if (descriptorsBuilder_ == null) {
          return descriptors_.get(index);  } else {
          return descriptorsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .org.hyperledger.chaintool.meta.InterfaceDescriptor descriptors = 1;</code>
       */
      public java.util.List<? extends org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptorOrBuilder> 
           getDescriptorsOrBuilderList() {
        if (descriptorsBuilder_ != null) {
          return descriptorsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(descriptors_);
        }
      }
      /**
       * <code>repeated .org.hyperledger.chaintool.meta.InterfaceDescriptor descriptors = 1;</code>
       */
      public org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor.Builder addDescriptorsBuilder() {
        return getDescriptorsFieldBuilder().addBuilder(
            org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor.getDefaultInstance());
      }
      /**
       * <code>repeated .org.hyperledger.chaintool.meta.InterfaceDescriptor descriptors = 1;</code>
       */
      public org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor.Builder addDescriptorsBuilder(
          int index) {
        return getDescriptorsFieldBuilder().addBuilder(
            index, org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor.getDefaultInstance());
      }
      /**
       * <code>repeated .org.hyperledger.chaintool.meta.InterfaceDescriptor descriptors = 1;</code>
       */
      public java.util.List<org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor.Builder> 
           getDescriptorsBuilderList() {
        return getDescriptorsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor, org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor.Builder, org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptorOrBuilder> 
          getDescriptorsFieldBuilder() {
        if (descriptorsBuilder_ == null) {
          descriptorsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor, org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor.Builder, org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptorOrBuilder>(
                  descriptors_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          descriptors_ = null;
        }
        return descriptorsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:org.hyperledger.chaintool.meta.Interfaces)
    }

    // @@protoc_insertion_point(class_scope:org.hyperledger.chaintool.meta.Interfaces)
    private static final org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.Interfaces DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.Interfaces();
    }

    public static org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.Interfaces getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Interfaces>
        PARSER = new com.google.protobuf.AbstractParser<Interfaces>() {
      public Interfaces parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new Interfaces(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<Interfaces> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Interfaces> getParserForType() {
      return PARSER;
    }

    public org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.Interfaces getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface InterfaceDescriptorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.hyperledger.chaintool.meta.InterfaceDescriptor)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional bytes data = 2;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code org.hyperledger.chaintool.meta.InterfaceDescriptor}
   */
  public  static final class InterfaceDescriptor extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.hyperledger.chaintool.meta.InterfaceDescriptor)
      InterfaceDescriptorOrBuilder {
    // Use InterfaceDescriptor.newBuilder() to construct.
    private InterfaceDescriptor(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private InterfaceDescriptor() {
      name_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private InterfaceDescriptor(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {

              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.internal_static_org_hyperledger_chaintool_meta_InterfaceDescriptor_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.internal_static_org_hyperledger_chaintool_meta_InterfaceDescriptor_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor.class, org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>optional bytes data = 2;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(2, data_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, data_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.hyperledger.chaintool.meta.InterfaceDescriptor}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.hyperledger.chaintool.meta.InterfaceDescriptor)
        org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.internal_static_org_hyperledger_chaintool_meta_InterfaceDescriptor_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.internal_static_org_hyperledger_chaintool_meta_InterfaceDescriptor_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor.class, org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor.Builder.class);
      }

      // Construct using org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        data_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.internal_static_org_hyperledger_chaintool_meta_InterfaceDescriptor_descriptor;
      }

      public org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor getDefaultInstanceForType() {
        return org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor.getDefaultInstance();
      }

      public org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor build() {
        org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor buildPartial() {
        org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor result = new org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor(this);
        result.name_ = name_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor) {
          return mergeFrom((org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor other) {
        if (other == org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes data = 2;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>optional bytes data = 2;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes data = 2;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:org.hyperledger.chaintool.meta.InterfaceDescriptor)
    }

    // @@protoc_insertion_point(class_scope:org.hyperledger.chaintool.meta.InterfaceDescriptor)
    private static final org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor();
    }

    public static org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<InterfaceDescriptor>
        PARSER = new com.google.protobuf.AbstractParser<InterfaceDescriptor>() {
      public InterfaceDescriptor parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new InterfaceDescriptor(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<InterfaceDescriptor> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<InterfaceDescriptor> getParserForType() {
      return PARSER;
    }

    public org.hyperledger.chaintool.meta.OrgHyperledgerChaintoolMeta.InterfaceDescriptor getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_hyperledger_chaintool_meta_GetInterfaceParams_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_hyperledger_chaintool_meta_GetInterfaceParams_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_hyperledger_chaintool_meta_GetInterfacesParams_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_hyperledger_chaintool_meta_GetInterfacesParams_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_hyperledger_chaintool_meta_Interfaces_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_hyperledger_chaintool_meta_Interfaces_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_hyperledger_chaintool_meta_InterfaceDescriptor_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_hyperledger_chaintool_meta_InterfaceDescriptor_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n+target/org.hyperledger.chaintool.meta." +
      "proto\022\036org.hyperledger.chaintool.meta\"\"\n" +
      "\022GetInterfaceParams\022\014\n\004name\030\001 \001(\t\"-\n\023Get" +
      "InterfacesParams\022\026\n\016IncludeContent\030\001 \001(\010" +
      "\"V\n\nInterfaces\022H\n\013descriptors\030\001 \003(\01323.or" +
      "g.hyperledger.chaintool.meta.InterfaceDe" +
      "scriptor\"1\n\023InterfaceDescriptor\022\014\n\004name\030" +
      "\001 \001(\t\022\014\n\004data\030\002 \001(\014b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_hyperledger_chaintool_meta_GetInterfaceParams_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_hyperledger_chaintool_meta_GetInterfaceParams_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_hyperledger_chaintool_meta_GetInterfaceParams_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_org_hyperledger_chaintool_meta_GetInterfacesParams_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_hyperledger_chaintool_meta_GetInterfacesParams_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_hyperledger_chaintool_meta_GetInterfacesParams_descriptor,
        new java.lang.String[] { "IncludeContent", });
    internal_static_org_hyperledger_chaintool_meta_Interfaces_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_hyperledger_chaintool_meta_Interfaces_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_hyperledger_chaintool_meta_Interfaces_descriptor,
        new java.lang.String[] { "Descriptors", });
    internal_static_org_hyperledger_chaintool_meta_InterfaceDescriptor_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_org_hyperledger_chaintool_meta_InterfaceDescriptor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_hyperledger_chaintool_meta_InterfaceDescriptor_descriptor,
        new java.lang.String[] { "Name", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
